### ISSUE TITLE
carpet too long?

### ISSUE THREAD

**Issue by mclt0568** [yxliang01/sleeping-human-text#2]
will it be better if its shorter? 
such as
`[(:D|-----]`

**Comment by yxliang01** [comment]
Hmm it depends on the size of the bed and the height of the man. I am thinking to write a python script to generate automatically according to these parameters.

**Comment by yxliang01** [comment]
#3 is considered as a fix to this issue. If you don't like the current length, then you can generate your own :stuck_out_tongue:
